### ISSUE TITLE
My workflow fails with no useful info

### ISSUE THREAD

**Issue by TekExplorer** [dacbd/create-issue-action#11]
Hello, I'm trying to use this action to copy issues, but running it results in an 
![image](https://user-images.githubusercontent.com/30291302/163757580-dedbe7f3-dfb0-4158-b1a3-1a39639b3bd7.png)
Which is decidedly unhelpful. Where do I even start debugging?

**Comment by dacbd** [comment]
I'm about to get on a plane but I will take a look at it when I land. Are
able to get a minimal workflow that reproduces the error. I can add
additional debug logging as well.

**Comment by TekExplorer** [comment]
[This](https://github.com/TekExplorer/featherdactyl.com/blob/main/.github/workflows/mirror_issues.yml) is the file i'm using. its fairly minimal already. All I'm doing is duplicating an issue, with the intent of doing this across repos later (public issues -> private repo)

**Comment by dacbd** [comment]
Try using owner and repo, with the example octo-org/my-repo

owner: octo-org
repo: my-repo

**Comment by TekExplorer** [comment]
That seems to have worked!

Although, now I want to add a comment to the original issue linking to the new one. Could you add an output that just outputs the new `issue` object?

**Comment by dacbd** [comment]
@TekExplorer thanks for using my action, I've created #12 and #13 based on your feedback

**Comment by TekExplorer** [comment]
o7

**Comment by dacbd** [comment]
That should be possible
