### ISSUE TITLE
Unable to create issue 

### ISSUE THREAD

**Issue by patilvishal1683** [dacbd/create-issue-action#33]
![image](https://user-images.githubusercontent.com/115708805/226304677-ffbe698d-6dc5-4d20-9225-91ee1fb0ae56.png)
Run dacbd/create-issue-action@main
  with:
    owner: patilvishal168[3](https://github.com/patilvishal1683/temp/actions/runs/4466827246/jobs/7845509615#step:2:3)
    repo: temp
    token: ***
    title: CPU Utilization
    body: This is a test issue created using the GitHub API and Python requests library.
Error: HttpError: Bad credentials
Error: Request to create new issue failed

**Comment by dacbd** [comment]
@patilvishal1683 I'm going to close this issue, if you need any more help feel free to reach out.
